version: '3'

services:
  gravity:
    image: onomy/cosmos-gravity-bridge-single-node-runner-rinkeby:local
    restart: on-failure
    container_name: cosmos-gravity-bridge-single-node-runner-rinkeby
    # volumes:
      # uncomment to pin gravity dir
      # - ./data:/home/testchain/gravity/data
      # uncomment to update gravity config in runtime
      # - ./scripts:/root/home/scripts
      # uncomment to update deployer in runtime
      # - ../../solidity/contract-deployer.ts:/go/src/github.com/onomyprotocol/cosmos-gravity-bridge/solidity/contract-deployer.ts
      # uncomment to update gravity config in runtime
      # - ./gravity_home:/root/home/testchain/gravity/.
    ports:
      # gravity
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 61278:61278
      - 9090:9090
      # ethereum
      - 8545:8545