name: Integration tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  happy-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up happy-path test
        run: tests/all-up-test.sh
  validator-out:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up test with a validator out
        run: tests/all-up-test.sh VALIDATOR_OUT
  valset-stress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up valset stress test
        run: tests/all-up-test.sh VALSET_STRESS
  batch-stress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up batch stress test
        run: tests/all-up-test.sh BATCH_STRESS
  v2-happy-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up batch stress test
        run: tests/all-up-test.sh V2_HAPPY_PATH
  arbitrary-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all up arbitrary logic test
        run: tests/all-up-test.sh ARBITRARY_LOGIC $ALCHEMY_ID
        env:
          ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
  orchestrator-keys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run orchestrator key setting test
        run: tests/all-up-test.sh ORCHESTRATOR_KEYS
  valset_update_rewards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the validator set update rewards test
        run: tests/all-up-test.sh VALSET_REWARDS
  london_hardfork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the London hardfork test
        run: tests/all-up-test.sh LONDON
