name: Integration tests

on:
  pull_request:
    branches: [master, main, test]

jobs:
  single-node-runner-test:
    runs-on: ubuntu-latest
    steps:
      - name: start master-cosmos-eth-node
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker run hello-world && docker rm -f $(docker ps -a -q) && docker rmi -f $(docker images -q) && docker run --name cosmos-gravity-bridge-single-node-runner -p 26656:26656 -p 26657:26657 -p 1317:1317 -p 61278:61278 -p 9090:9090 -p 8545:8545 -d --restart on-failure shivachaudhary10/single-node-runner:v-1
          host: ${{ secrets.MASTER_NODE_HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
